export default {
  0: "Clear skys",
  1: "Mainly Clear",
  2: "Partly Cloudy",
  3: "Overcast",
  45: "Fog",
  48: "Depositing rime fog",
  51: "Drizzle: Light",
  53: "Drizzle: Moderate",
  55: "Drizzle: Dense",
  56: "Freezing Drizzle: Light",
  57: "Freezing Drizzle: Dense",
  61: "Rain: Slight",
  63: "Rain: Moderate",
  65: "Rain: Heavy",
  66: "Freezing rain: Light",
  67: "Freezing rain: Heavy",
  71: "Snow fall: Slight",
  73: "Snow fall: Moderate",
  75: "Snow fall: Heavy",
  77: "Snow grains",
  80: "Rain showers: Slight",
  81: "Rain showers: Moderate",
  82: "Rain showers: V I O L E N T",
  85: "Snow showers: Slight",
  86: "Snow showers: Heavy",
  95: "Thuderstorm: Slight/Moderate",
  96: "Thuderstorm with slight hail",
  99: "Thuderstorm with heavy hail",
} as {
  [key: string]: string
}